# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u5e10\u53f7')),
                ('password', models.CharField(max_length=200, verbose_name='\u5bc6\u7801')),
                ('Full_name', models.CharField(max_length=40, null=True, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=2, null=True, verbose_name='\u6027\u522b')),
                ('living_address', models.CharField(default=b'\xe5\xb9\xbf\xe4\xb8\x9c\xe6\xb7\xb1\xe5\x9c\xb3', max_length=200, verbose_name='\u4f4f\u5740')),
                ('email_address', models.EmailField(max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('identity', models.CharField(choices=[('\u7ba1\u7406\u5458', '\u7ba1\u7406\u5458'), ('\u5de5\u4f5c\u4eba\u5458', '\u5de5\u4f5c\u4eba\u5458'), ('\u5fd7\u613f\u8005', '\u5fd7\u613f\u8005'), ('\u4e50\u961f', '\u4e50\u961f'), ('\u6e38\u5ba2', '\u6e38\u5ba2')], default='\u6e38\u5ba2', max_length=5, verbose_name='\u8eab\u4efd')),
                ('headImg', models.FileField(default=b'static/upload/default.jpg', upload_to=b'static/upload/')),
                ('creat_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
    ]
