# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
