# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170428_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u59d3\u6c0f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='\u5e10\u53f7'),
        ),
    ]
