# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('B', 'Boss'), ('W', 'Worker'), ('V', 'Volunteer'), ('C', 'Cooperation')], max_length=2, null=True, verbose_name='\u8eab\u4efd'),
        ),
    ]
